### ISSUE TITLE
Debugging: display value in tooltip when hovering over variables

### ISSUE THREAD

**Issue by neuronix** [BowlerHatLLC/vscode-swf-debug#22] opened 2020-12-14 10:12 UTC
When debugging and pausing or hitting a breakpoint, when hovering the mouse over a variable, one would expect to see the value.

This currently seems to only work for parameters in a method. Any instance attribute values or local variables do not display the callout with the value, one has to use the tree view on the left, which is quite tedious.

Is this something you can fix? Is my setup incorrect?

Thanks for your help

**Comment by Adolio** [comment] 2021-12-17 13:31
I'm very interested by this feature too.

**Comment by Adolio** [comment] 2021-12-17 13:34
This task is actually a duplicate of #19

**Comment by Adolio** [comment] 2022-07-10 17:26
Hey Josh, any chance to do further investigations on this one - maybe something has changed in the meantime?

At my end the values of the `private` members can be inspected from the `watch` tab but not when mouse hovering the variable.

This feature would be pretty useful from my side.

Thanks in advance for your precious time.

**Closed** 2023-06-23 19:02 UTC
Labels: enhancement
